sudo: required
dist: precise
group: edge

language: android

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - TEST_SUITE="codenarc integTest"
  - TEST_SUITE="perfTest --tests *.PmdPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.FindbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.CheckstylePerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.CpdPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.PmdPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"
  - TEST_SUITE="perfTest --tests *.FindbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"
  - TEST_SUITE="perfTest --tests *.CheckstylePerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"
  - TEST_SUITE="perfTest --tests *.CpdPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

branches:
  only:
    - development
    - staging
    - /^support-.*$/

script:
    - ./gradlew assemble $TEST_SUITE
