sudo: required
dist: precise
group: edge

language: android

cache:
  directories:
    - $HOME/.gradle

before_cache:
  # Remove daemon logs, bin databases, and lockfiles
  - rm -rf $HOME/.gradle/daemon/
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - TEST_SUITE="codenarc integTest"
  # analyze each tool independently
  - TEST_SUITE="perfTest --tests *.PmdPerfTest.*"
  - TEST_SUITE="perfTest --tests *.CheckstylePerfTest.*"
  - TEST_SUITE="perfTest --tests *.CpdPerfTest.*"
  # split findbugs tests as those are slower and timeout
  - TEST_SUITE="perfTest --tests *.FindbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.FindbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

branches:
  only:
    - development
    - staging
    - /^support-.*$/

script:
    - ./gradlew assemble $TEST_SUITE
